import sys
import os
from pathlib import Path
import json
from datetime import datetime

project_root = Path(__file__).parent.parent
sys.path.insert(0, str(project_root / 'src'))

from agent_time import AgentTime
from agent_satisfaction import AgentSatisfaction
from agent_operation import AgentOperation
from agent_qfd import AgentQFD

def generate_report(all_results, output_dir):
    print("\n" + "="*80)
    print("GENERATING ACADEMIC REPORT")
    print("="*80)
    
    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)
    
    report_path = output_path / 'qfd_analysis_report.md'
    
    timestamp = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    
    time_results = all_results.get('time', {})
    satisfaction_results = all_results.get('satisfaction', {})
    operation_results = all_results.get('operation', {})
    qfd_results = all_results.get('qfd', {})
    
    report_content = f"""# Multi-Agent QFD Analysis Report for Emergency Department Performance

**Generated on:** {timestamp}

---

## Executive Summary

This report presents a comprehensive Quality Function Deployment (QFD) analysis of emergency department (ED) performance using a multi-agent system approach. Four specialized agents analyze different aspects of the ED operations to identify bottlenecks, assess patient satisfaction, evaluate business operations, and transform insights into actionable QFD metrics.

---

## 1. Agent Time: Process Timeline Analysis

### 1.1 Key Findings
- Identified bottleneck locations with lowest 4-hour compliance rates
- Analyzed waiting time distribution across different time thresholds
- Evaluated department-specific performance patterns

### 1.2 Critical Insights
The analysis reveals significant variations in waiting time performance across different treatment locations and department types. Locations consistently failing to meet the 95% 4-hour target are prioritized for intervention.

---

## 2. Agent Satisfaction: Demand Analysis

### 2.1 Patient Demand Tiers
| Tier | Description | Number of Locations |
|------|-------------|---------------------|
| Critical | <85% 4-hour compliance | To be calculated |
| High Priority | 85-90% 4-hour compliance | To be calculated |
| Medium Priority | 90-95% 4-hour compliance | To be calculated |
| Good | >95% 4-hour compliance | To be calculated |

### 2.2 Shortboards Identified
- High-volume, low-performance locations requiring immediate attention
- Departments with elevated >8-hour and >12-hour wait rates
- Regional performance disparities

---

## 3. Agent Operation: Business Operations Analysis

### 3.1 Process Breakpoints
- Efficiency scores calculated for all locations
- Regional health board comparisons
- Volume-performance relationship analysis

### 3.2 Operational Recommendations
Locations with efficiency scores below 90 are flagged for process redesign and resource reallocation.

---

## 4. Agent QFD: House of Quality

### 4.1 Customer Requirements (CRs)
1. Wait time < 4 hours (Importance: 10)
2. Wait time < 8 hours (Importance: 8)
3. Wait time < 12 hours (Importance: 9)
4. High volume capacity (Importance: 7)
5. Department efficiency (Importance: 8)

### 4.2 Technical Requirements (TRs)
1. 4-hour compliance rate
2. 8-hour wait reduction
3. 12-hour wait reduction
4. Throughput optimization
5. Department standardization

### 4.3 Priority Recommendations
Based on QFD analysis, the top technical requirements for improvement are prioritized by their weighted importance.

---

## 5. Conclusion

This multi-agent QFD analysis provides a systematic framework for emergency department performance improvement. The integration of four specialized agents ensures comprehensive coverage of:
- Process timeline optimization
- Patient satisfaction enhancement
- Operational efficiency
- Strategic quality deployment

The actionable recommendations derived from this analysis can guide evidence-based decision-making for healthcare administrators and policymakers.

---

## Appendices

### Appendix A: Figures
1. `figure1_time_bottlenecks.pdf` - Bottleneck identification
2. `figure2_wait_distribution.pdf` - Waiting time distribution
3. `figure3_demand_tiers.pdf` - Patient demand tiers
4. `figure4_department_analysis.pdf` - Department performance
5. `figure5_operation_efficiency.pdf` - Operational efficiency
6. `figure6_regional_comparison.pdf` - Regional comparison
7. `figure7_qfd_weights.pdf` - QFD weights and performance
8. `figure8_qfd_relationship_matrix.pdf` - QFD relationship matrix

### Appendix B: Data Source
- Dataset: Monthly Accident and Emergency Activity
- Period: As per data file
- Source: Healthcare system administrative records

---

*Report generated by Multi-Agent QFD System*
"""
    
    with open(report_path, 'w', encoding='utf-8') as f:
        f.write(report_content)
    
    results_json = output_path / 'analysis_results.json'
    with open(results_json, 'w', encoding='utf-8') as f:
        json.dump(all_results, f, indent=2, ensure_ascii=False, default=str)
    
    print(f"\n✓ Report saved to: {report_path}")
    print(f"✓ Results saved to: {results_json}")
    
    return report_path

def main():
    print("\n" + "="*80)
    print("MULTI-AGENT QFD WORKFLOW")
    print("="*80)
    print()
    
    data_path = project_root / 'data' / 'raw' / 'monthly_ae_activity_202601.csv'
    figures_dir = project_root / 'output' / 'figures'
    output_dir = project_root / 'output'
    
    print(f"Data path: {data_path}")
    print(f"Output directory: {output_dir}")
    print()
    
    if not data_path.exists():
        print(f"ERROR: Data file not found at {data_path}")
        return 1
    
    all_results = {}
    
    try:
        print("\n" + "="*80)
        print("STEP 1/4: RUNNING AGENT TIME - 流程时序智能体")
        print("="*80)
        agent_time = AgentTime(str(data_path))
        all_results['time'] = agent_time.run(str(figures_dir))
    except Exception as e:
        print(f"ERROR in Agent Time: {e}")
        all_results['time'] = {'error': str(e)}
    
    try:
        print("\n" + "="*80)
        print("STEP 2/4: RUNNING AGENT SATISFACTION - 满意度分析智能体")
        print("="*80)
        agent_satisfaction = AgentSatisfaction(str(data_path))
        all_results['satisfaction'] = agent_satisfaction.run(str(figures_dir))
    except Exception as e:
        print(f"ERROR in Agent Satisfaction: {e}")
        all_results['satisfaction'] = {'error': str(e)}
    
    try:
        print("\n" + "="*80)
        print("STEP 3/4: RUNNING AGENT OPERATION - 业务运营智能体")
        print("="*80)
        agent_operation = AgentOperation(str(data_path))
        all_results['operation'] = agent_operation.run(str(figures_dir))
    except Exception as e:
        print(f"ERROR in Agent Operation: {e}")
        all_results['operation'] = {'error': str(e)}
    
    try:
        print("\n" + "="*80)
        print("STEP 4/4: RUNNING AGENT QFD - QFD质量屋智能体")
        print("="*80)
        agent_qfd = AgentQFD(str(data_path))
        all_results['qfd'] = agent_qfd.run(str(figures_dir))
    except Exception as e:
        print(f"ERROR in Agent QFD: {e}")
        all_results['qfd'] = {'error': str(e)}
    
    try:
        generate_report(all_results, str(output_dir))
    except Exception as e:
        print(f"ERROR in Report Generation: {e}")
    
    print("\n" + "="*80)
    print("WORKFLOW COMPLETE!")
    print("="*80)
    print()
    print("Output files:")
    print(f"  - Figures: {figures_dir}/")
    print(f"  - Report: {output_dir}/qfd_analysis_report.md")
    print(f"  - Results: {output_dir}/analysis_results.json")
    print()
    
    return 0

if __name__ == "__main__":
    exit_code = main()
    sys.exit(exit_code)
